FROM alpine:latest

RUN apk update
RUN apk add --no-cache curl inotify-tools bash

ENV GLUETUN_SERVER=localhost
ENV GLUETUN_CONTROL_PORT=8000
ENV GLUETUN_AUTH_METHOD=apikey
ENV GLUETUN_APIKEY
ENV GLUETUN_USERNAME
ENV GLUETUN_PASSWORD
ENV QBITTORRENT_SERVER=localhost
ENV QBITTORRENT_PORT=8080
ENV QBITTORRENT_USER=admin
ENV QBITTORRENT_PASS=adminadmin
ENV HTTP_S=http

COPY ./start.sh ./start.sh
RUN chmod 770 ./start.sh

CMD ["./start.sh"]
